### PR TITLE
Parallel renaming

### PR DESCRIPTION
**Pull request by nulltoken**
cf https://github.com/libgit2/libgit2sharp/pull/963#issuecomment-75879427

### CODE REVIEW

**Comment by ThomasBarnekow** [comment]
@nulltoken Merged on the command line but this somehow does not show here.

**Comment by nulltoken** [comment]
@ThomasBarnekow Weird.

Below the test failure...

```
Xunit.Sdk.EqualExceptionAssert.Equal() Failure

Position: First difference is at position 6

Expected: List<Commit> { 80497f3178707b80a8068042d139baadf8579984, b4c59f990d85c56f3bfa100fc47bfdd73a574264, 21d9ed55a04d40a1122e9bda88d50e4122a58f30, 0bdefb1edc891a1661827343724617b661b52ca6, bc2a9618198d782e3ff8727db0c61a673488ca2a, 11dc5bf68441567f6833ad8cee67bb5da66f524c, b91bc89567b2b8c1f1bff2d820cc822a12cd2c69, 99bf6e3ebcb0a302076bc4ccf22b9c21f4c09af0, 7363031cdf1bfbccaef447cacb81f41b232714fb }

Actual:   WhereSelectEnumerableIterator<FileHistoryEntry, Commit> { 80497f3178707b80a8068042d139baadf8579984, b4c59f990d85c56f3bfa100fc47bfdd73a574264, 21d9ed55a04d40a1122e9bda88d50e4122a58f30, 0bdefb1edc891a1661827343724617b661b52ca6, bc2a9618198d782e3ff8727db0c61a673488ca2a, 11dc5bf68441567f6833ad8cee67bb5da66f524c, 99bf6e3ebcb0a302076bc4ccf22b9c21f4c09af0, 7363031cdf1bfbccaef447cacb81f41b232714fb }
   at LibGit2Sharp.Tests.FileHistoryFixture.CanFollowBranches(String specificRepoPath) in FileHistoryFixture.cs: line 244
```

...and the output that git command line produces when ran against the created test repository

```
$ git log --follow Test.txt.new
commit 80497f3178707b80a8068042d139baadf8579984
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:13:27 2011 +0200

    10. Changed on master

commit b4c59f990d85c56f3bfa100fc47bfdd73a574264
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:10:27 2011 +0200

    8. Changed on master

commit 21d9ed55a04d40a1122e9bda88d50e4122a58f30
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:09:27 2011 +0200

    7. Changed on next-fix

commit 0bdefb1edc891a1661827343724617b661b52ca6
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:07:27 2011 +0200

    6. Changed on master

commit bc2a9618198d782e3ff8727db0c61a673488ca2a
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:04:27 2011 +0200

    4. Changed on master

commit 11dc5bf68441567f6833ad8cee67bb5da66f524c
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:03:27 2011 +0200

    3. Changed on fix

commit b91bc89567b2b8c1f1bff2d820cc822a12cd2c69
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:02:27 2011 +0200

    2. Changed on master

commit 99bf6e3ebcb0a302076bc4ccf22b9c21f4c09af0
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:01:27 2011 +0200

    1. Changed on fix

commit 7363031cdf1bfbccaef447cacb81f41b232714fb
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 10:59:27 2011 +0200

    0. Initial commit for this test

$ git log --follow --topo-order Test.txt.new
commit 80497f3178707b80a8068042d139baadf8579984
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:13:27 2011 +0200

    10. Changed on master

commit 21d9ed55a04d40a1122e9bda88d50e4122a58f30
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:09:27 2011 +0200

    7. Changed on next-fix

commit b4c59f990d85c56f3bfa100fc47bfdd73a574264
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:10:27 2011 +0200

    8. Changed on master

commit 0bdefb1edc891a1661827343724617b661b52ca6
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:07:27 2011 +0200

    6. Changed on master

commit 11dc5bf68441567f6833ad8cee67bb5da66f524c
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:03:27 2011 +0200

    3. Changed on fix

commit 99bf6e3ebcb0a302076bc4ccf22b9c21f4c09af0
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:01:27 2011 +0200

    1. Changed on fix

commit bc2a9618198d782e3ff8727db0c61a673488ca2a
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:04:27 2011 +0200

    4. Changed on master

commit b91bc89567b2b8c1f1bff2d820cc822a12cd2c69
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 11:02:27 2011 +0200

    2. Changed on master

commit 7363031cdf1bfbccaef447cacb81f41b232714fb
Author: A. U. Thor <thor@valhalla.asgard.com>
Date:   Thu Jun 16 10:59:27 2011 +0200

    0. Initial commit for this test

$
```

**Comment by nulltoken** [comment]
@ThomasBarnekow Just pushed a proposal.

This should avoid the manual conflict resolution and should ease the building of more complex commit DAGs by not involving the working directory, nor the index.

Instead, we directly work against the odb and provide each Commit with the list of its parents.

**Comment by ThomasBarnekow** [comment]
@nulltoken Cool, merged locally and will have a look in the evening.

**Pull request merged**
